language: java

services:
    - docker
    
script:
    - make docker-login
    - make 
    - make TAG=${TRAVIS_BUILD_NUMBER} tag
    - make TAG=${TRAVIS_BUILD_NUMBER} push-tag
    - make push-latest

