language: java

services:
    - docker

cache:
    - $HOME/.m2
 
script:
    - make
    - make docker-login
    - make TAG=${TRAVIS_BUILD_NUMBER} tag
    - make TAG=${TRAVIS_BUILD_NUMBER} push-tag
    - make push-latest

